### ISSUE TITLE
Both main and master branches exist

### ISSUE THREAD

**Issue by pdecat** [rtx-plugins/rtx-nodejs#5]
Hi @jdxcode, 

did you mean to push the fix for #4 in `master` branch instead of `main`?

![image](https://user-images.githubusercontent.com/318490/233771422-a9211506-25c7-4543-9152-20ecec8486a3.png)

**Comment by jdx** [comment]
yeah it's unfortunate there are people on both of these branches so I need to keep them synced.

This repo will soon no longer be necessary though since there is a core plugin that's currently experimental so it's a temporary problem.
